### ISSUE TITLE
html bug

### ISSUE THREAD

**Issue by y377** [abdheshnayak/mdeditor#1]
**Describe the bug**
Hello, thank you very much for developing such a powerful MD editor, but when converted to HTML, the code is compressed into one line

**To Reproduce**
I think if I can improve this error and output the HTML code as it is, it will be a very powerful online editor! Thank you very much.
**Expected behavior**
I use your online [https://kamla.com.np/app/mdeditor/]https://kamla.com.np/app/mdeditor/)
- If you can add code highlighting parameters to your online editor, I want to transfer HTML directly, which is the most powerful online editor on earth
[code highlight](https://highlightjs.org/)
**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser chrome, 84.0.4147.125

![image](https://user-images.githubusercontent.com/58632405/97320890-3dc82a80-18a9-11eb-901c-32df297b66bd.png)

**Additional context**

**Comment by abdheshnayak** [comment]
Thankyou for using MD editor...
Every bugs and suggestions are reviewed and the md editor updated... please check it...and let me know if anything left to update....

**Comment by y377** [comment]
![image](https://user-images.githubusercontent.com/58632405/97378202-c4f2be00-18fc-11eb-9a68-2a06b7b7c342.png)
I'm glad you've made some improvements. You just programmed the nginx code segment in the screenshot into normal inline text. I mean, if you can output the original code format without manually modifying the converted HTML, it will be the most perfect

**Comment by abdheshnayak** [comment]
I tested and not gotten any error in the editor so please include the video of the error in detail if possible.
**I tested in these steps and worked fine for me:**
**STEP 1:** this is the markdown code in the editor

![pic-selected-201028-0835-06](https://user-images.githubusercontent.com/54141029/97386503-f7e78280-18f9-11eb-8742-68683fe35e0d.png)

**STEP 2:** this is converted into HTML and copied

![pic-selected-201028-0835-25](https://user-images.githubusercontent.com/54141029/97386579-22d1d680-18fa-11eb-974c-abcb46a2c04a.png)

**STEP 3 :** pasted into the editor
![pic-selected-201028-0840-16](https://user-images.githubusercontent.com/54141029/97386611-2feec580-18fa-11eb-8db5-90f3a06e50a5.png)

**STEP 4:** checking the output in the browser.

![pic-selected-201028-0840-30](https://user-images.githubusercontent.com/54141029/97386634-3d0bb480-18fa-11eb-83a3-3963c9818148.png)

**So finally I got everything right so please explain your issue in detail.**

**Comment by y377** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Abdhesh Nayak"<notifications@github.com&gt;; 
发送时间: 2020年10月28日(星期三) 中午11:22
收件人: "abdheshnayak/mdeditor"<mdeditor@noreply.github.com&gt;; 
抄送: "绣花针"<csever@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [abdheshnayak/mdeditor] html bug (#1)





 
I tested and not gotten any error in the editor so please include the video of the error in detail if possible.
 I tested in these steps and worked fine for me:
 STEP 1: this is the markdown code in the editor
 

 
STEP 2: this is converted into HTML and copied
 

 
STEP 3 : pasted into the editor
 
 
STEP 4: checking the output in the browser.
 

 
So finally I got everything right so please explain your issue in detail.
 
&mdash;
